export const projectsArray = [
    {
        name: "Number Blast", 
        descr1: "Welcome to number Blast, a reaction based number game designed to test your speed against the clock!",
        descr2: "Built in Javascript with React, Firebase and tsParticles, Number Blast offers a fun and frantic gaming experience to challenge you and your freinds! How fast are you under pressure?",
        descr3Bold: "States of Play.",
        descr3: "Built in React with heavy use of state, effect and callback hooks to handle evolving game, level, timer and styling changes.",
        descr4Bold: "Global Leaderboard.",
        descr4: "What's wrong with a friendly competition? Maybe a lot when I can't even crack the top five of my own game any more! Do you have what it takes to reach the top spot?",
        descr5Bold: "Interactive Styling.",
        descr5: "Those background numbers are not just for show. Using tsParticles, they are fully interactive and even add to the frantic pace of higher game levels. Have you got what it takes to remain calm?",
        link: "https://number-blast.netlify.app/",
        linkDescr: "Try it for yourself!",
        github: "https://github.com/DanielCouperthwaite/number-blast",
    },
    {
        name: "The Guitar Shop", 
        descr1: "Welcome to The Guitar Shop, a simple website to highlight stock details available from different locations.",
        descr2: "Built in C# with ASP .NET and Bootstrap CSS, The Guitar Shop offers a frontend source of information for guitar availability, locations and descriptions.",
        descr3Bold: "Built for Scalability. ",
        descr3: "Working from an internal C# list of guitars, the site loops through to display the details of each at your fingertips.",
        descr4Bold: "Dynamic ASP Routing. Need",
        descr4: "Need a thousand different pages of individual guitars? No problem! Each information page and url is created dynamically as the user chooses them.",
        descr5Bold: "Bootstrap Styling. ",
        descr5: "Clean and crisp, Bootstrap CSS allows guitars to be displayed in a simple and clear way.",
        link: "",
        linkDescr: "",
        github: "https://github.com/DanielCouperthwaite/guitar-shop",
    },
    {
        name: "Love Birds", 
        descr1: "Built as final project of the Northcoders Bootcamp, Love Birds is a fun and interactive application designed to keep the spark in long distance relationships.",
        descr2: "Built in Typescript with Firebase, React Native and Tailwind CSS, Love Birds allows users to send images, videos and more to their loved ones. Upon receiving their message, users must answer a quiz question or play a game to 'hatch their egg' and receive their prize.",
        descr3Bold: "Built for complexity. ",
        descr3: "Typsescript enables a greater confidence in the complexity and amount of components used, allowing us to pinpoint exactly where errors were hiding!",
        descr4Bold: "Agile Methodologies.",
        descr4: "Who doesn't love a good plan? Beginning with user stories and functionality in mind, we followed a structure of allocating tickets, collaborating between our team, offering feedback and reviewing progress each day.",
        descr5Bold: "",
        descr5: "",
        link: "https://northcoders.com/projects/june-2023/love-birds",
        linkDescr: "Video Demo Here",
        github: "https://github.com/DanielCouperthwaite/love-birds",
    },
    {
        name: "Just News", 
        descr1: "What is worse than sifting through ad after ad in search of the headlines? Eurgh! There has to be a better way! How about a site for those wanting articles in a simple format? Just News provides Just that, Just when you need it, Just about!",
        descr2: "Built in Javascript with React, Vite and CSS, Just News requests information from the NC_News Api (see below) and renders articles by topic... Or in a great big list if that's more your thing. We don't judge here.",
        descr3Bold: "Responsive and dynamic.",
        descr3: "Just News is built to function on any size of screen, even switching automatically between light and dark modes depending on the preferences of users and browsers.",
        descr4Bold: "Optimistic rendering.",
        descr4: "Who has the time to wait for a comment to be posted to an api before seeing it in all its online glory? All comments and votes offer feedback immediately.",
        descr5Bold: "Safe and secure.",
        descr5: "Built to protect against malicious sql injections, you can trust that your comment contents are safe. Trust me, my brother is a principal engineer at ARM and he's already tried his best to break it.",
        link: "https://just-news8118.netlify.app/articles",
        linkDescr: "Try it for yourself!",
        github: "https://github.com/DanielCouperthwaite/nc_news",
    },
    {
        name: "Just News API", 
        descr1: "As pretty as they might be, some of the best sites in the world would be nowhere without a functioning server and database.",
        descr2: "Built with a PostgreSQL, Express JS and Node JS, this api serves the articles used in my Just News site (see above.) You can try it yourself with the buttons below. There is a list of all the available endpoints, or a couple of example requests already written out:",
        descr3Bold: "Tried and Tested.",
        descr3: "Tested with Jest.js to ensure each endpoint returns relevant, requested, complete content.",
        descr4Bold: "Errors? Who needs 'em?",
        descr4: "Able to check requests against contents and offer feedback. See for yourself with this request for an article that does not exist:",
        descr5Bold: "",
        descr5: "",
        link: "https://nc-news-qkml.onrender.com/api/",
        linkDescr: "Endpoint Descriptions Here",
        link2: "https://nc-news-qkml.onrender.com/api/articles",
        link2Descr: "/api/articles",
        link3: "https://nc-news-qkml.onrender.com/api/articles/6/comments",
        link3Descr: "/api/articles/6/comments",
        link4: "/api/articles/2112",
        link4Descr: "https://nc-news-qkml.onrender.com/api/articles/2112",
        github: "https://github.com/DanielCouperthwaite/NC-News-Backend-Project",
    },
]


// {
    //     name: "", 
    //     descr1: "",
    //     descr2: "",
    //     descr3Bold: "",
    //     descr3: "",
    //     descr4Bold: "",
    //     descr4: "",
    //     descr5Bold: "",
    //     descr5: "",
    //     link: "",
    //     linkDescr: "",
    //     github: "",
    // },